test: &test
  machine:
    image: circleci/classic:latest
    docker_layer_caching: true

jobs:
  stylecheck_and_test:
    <<: *test
    steps:
      - checkout
      - run:
          name: Check coding style
          command: |
            flake8
      #- run:
      #    name: Build Docker image for test
      #    command: |
      #      make build-test
      #- run:
      #    name: Run test
      #    command: |
      #      make test-ci
      #- run:
      #    name: Upload coverage
      #    command: |
      #      bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

workflows:
  version: 2
  build-workflow:
    jobs:
      - stylecheck_and_test:
          context: org-global
          filters:
            branches:
              only:
                  - /.*/
            tags:
              only: /.*/
